"""empty message

Revision ID: 565efae2a702
Revises: 5fb1763e07fc
Create Date: 2020-09-09 04:17:30.451556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565efae2a702'
down_revision = '5fb1763e07fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscription', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscription', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'group_id')
    op.drop_table('group')
    # ### end Alembic commands ###
