"""empty message

Revision ID: daf94a5ad266
Revises: 565efae2a702
Create Date: 2020-09-14 02:09:16.495939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf94a5ad266'
down_revision = '565efae2a702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'group', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='unique')
    # ### end Alembic commands ###
